# Generated by Django 4.1.2 on 2022-10-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_film_genre_film_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='kinopoisk_id',
            field=models.IntegerField(default=0),
        ),
    ]
