# Generated by Django 4.1.2 on 2022-10-27 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_film_kinopoisk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
